# Generated by Django 5.1.6 on 2025-02-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_accounts',
        ),
    ]
